<?php
/**
 * Created by PhpStorm.
 * User: gaokai
 * Date: 2019-10-23
 * Time: 14:53
 */

namespace kaikaige\layui\grid;

use yii\base\Component;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;

class RowButton extends Component
{
    public $title;

    public $url;

    public $options;

    public $event;

    public $js;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->options['lay-event'] =$this->event;
    }

    public function tag() {
        return Html::beginTag('a', $this->options).$this->title.Html::endTag('a');
    }
}