<?php
namespace kaikaige\layui\components;

use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;

class SearchActiveForm extends \yii\widgets\ActiveForm
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->options = ArrayHelper::merge([
            'style'=>'display:inline;',
            'class'=>'layui-form search-form',
            'lay-filter'=>'searchForm'
        ], $this->options);

        $this->fieldConfig = ArrayHelper::merge([
            'template' => '<div class="layui-inline">{label}<div class="layui-input-inline">{input}</div></div>',
            'labelOptions' => ['class' => 'layui-form-label'],
            'inputOptions' => ['class'=>'layui-input'],
            'options'=>['tag'=>false]
        ], $this->fieldConfig);
    }
}