<?php

namespace kaikaige\layui\actions;

use yii\base\Action;
use yii\helpers\Url;

/**
 * Created by PhpStorm.
 * User: gaokai
 * Date: 2019-11-19
 * Time: 10:28
 */

class IndexAction extends Action
{
    public $defaultUrl = ['site/index'];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run() {
        $this->controller->layout = false;
        return $this->controller->render('@kaikaige/layui/views/home/index', [
            'defaultUrl' => Url::to($this->defaultUrl),
        ]);
    }
}